language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install argparse catkin-pkg distribute rosdistro rospkg PyYAML
# command to run tests
script:
  - nosetests -s --tests test
notifications:
  email: false
